import type { NextApiRequest, NextApiResponse } from 'next'
import { getSession } from 'next-auth/react'

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  try {
    const { user } = (await getSession({ req })) as any
    const { book, songs } = req.body

    // get track uris
    let uris = ''
    songs.map((song) => {
      uris += `${song.uri},`
    })
    uris = uris.slice(0, -1)

    // create playlist
    let response = await fetch(`https://api.spotify.com/v1/users/${user.user.id}/playlists`, {
      method: 'POST',
      body: JSON.stringify({
        name: `${book} vibez`,
        description: 'This playlist is generated by readingmood.',
        public: false,
      }),
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${user.accessToken}`,
      },
    })
    const playlist = await response.json()
    console.log('@@@ playlist', playlist)

    // add songs to the created playlist
    response = await fetch(
      `	https://api.spotify.com/v1/playlists/${playlist.id}/tracks?uris=${encodeURIComponent(uris)}`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${user.accessToken}`,
        },
      }
    )

    const result = await response.json()
    console.log('@@@ result', result)

    res.status(200).json({ result, playlistUrl: playlist.external_urls.spotify })
  } catch (error) {
    throw error
  }
}
